import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
// import { use } from 'react'

type Params = Promise<{ slug: string }>

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={cn("relative h-full font-sans antialiased")}>
        <main className="relative flex flex-col min-h-screen">
          <SessionProvider>
            <Navbar />
            <Toaster richColors position="top-center" />
            <div className="flex-grow flex-1">{children}</div>
          </SessionProvider>
        </main>
      </body>
    </html>
  );
}
